### PR TITLE
Rich text

### PR DESCRIPTION
**Pull request by VyrCossont**
### Summary

Adds rich text support for statuses. Read-only: authoring to come later once I've worked out how to detect rich text support in backends.

### CODE REVIEW

**Comment by VyrCossont** [comment]
@bdube This one applies on top of the PR for bdube/metatext#18.

**Comment by VyrCossont** [comment]
Looks like I'll need to rebase this one

**Comment by bdube** [comment]
Sorry about that. I should have waited to mess with the actions.

**Comment by VyrCossont** [comment]
Rebased and moved to bdube/metatext#19.

**Pull request closed without merging**
